In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
%load_ext autoreload
%autoreload 2

Data Generation
===

In [2]:
num_samples, num_features = 10, 5

In [27]:
np.random.seed(11)
data = np.random.rand(num_samples, num_features)

Solution
===

In [28]:
print(data)

[[0.18026969 0.01947524 0.46321853 0.72493393 0.4202036 ]
 [0.4854271  0.01278081 0.48737161 0.94180665 0.85079509]
 [0.72996447 0.10873607 0.89390417 0.85715425 0.16508662]
 [0.63233401 0.02048361 0.11673727 0.31636731 0.15791231]
 [0.75897959 0.81827536 0.34462449 0.3187988  0.11166123]
 [0.08395314 0.71272594 0.5995434  0.05567368 0.47979728]
 [0.40167648 0.847979   0.71784918 0.60206405 0.55238382]
 [0.9491024  0.98667333 0.33805405 0.23987468 0.79643575]
 [0.06368643 0.36461564 0.0700228  0.31936771 0.0703826 ]
 [0.29026367 0.79010112 0.90540032 0.79262139 0.56181871]]


In [29]:
assert isinstance(data,np.ndarray)

In [30]:
data.mean()

0.47058736743468244

In [31]:
data.std()

0.30518160095210684

In [35]:
def standardize(x):
    '''
    '''
    assert isinstance(x,np.ndarray), 'Not an np.ndarray'
    for i in range(0,x.shape[1]):
        
        mean = x[:,i].mean()
        std = x[:,i].std()

        print('Mean:  ',mean)
        print('Std: ',std)

        x[:,i] = x[:,i] - mean
        x[:,i] = x[:,i] / std

    return x

std_data = standardize(data)

Mean:   0.45756569788586854
Std:  0.289950658269685
Mean:   0.46818461286267005
Std:  0.3805479264085956
Mean:   0.4936725812514167
Std:  0.2757041548498087
Mean:   0.516866243910053
Std:  0.28823967763241476
Mean:   0.416647701263404
Std:  0.26820991836924285


In [37]:
def standardize(x):
    '''
    '''
    assert isinstance(x,np.ndarray), 'Not an np.ndarray'
    mean = x.mean(0)
    std = x.std(0)
    
    x = x - mean
    x = x / std

    return x

std_data = standardize(data)

In [38]:
print(std_data, "\n\n", np.mean(std_data, axis=0), "\n\n", np.std(std_data, axis=0))

[[-0.95635585 -1.17911396 -0.11045918  0.7218565   0.01325791]
 [ 0.09609014 -1.1967055  -0.02285411  1.47426063  1.61868506]
 [ 0.93946596 -0.94455525  1.4516705   1.18057308 -0.9379261 ]
 [ 0.60275192 -1.17646417 -1.36717313 -0.69559796 -0.96467497]
 [ 1.03953511  0.91996493 -0.54060879 -0.68716233 -1.13711853]
 [-1.28853839  0.64260322  0.38400152 -1.6000315   0.23544834]
 [-0.19275423  0.99801985  0.81310562  0.29557973  0.50608166]
 [ 1.69524257  1.36247942 -0.56444028 -0.96097653  1.41601047]
 [-1.3584355  -0.27215749 -1.53661006 -0.68518859 -1.29102275]
 [-0.57700173  0.84592896  1.49336792  0.95668696  0.54125891]] 

 [-3.33066907e-17 -4.44089210e-17  2.22044605e-17  1.11022302e-17
 -2.22044605e-17] 

 [1. 1. 1. 1. 1.]


In [34]:
std_data.mean()
std_data.std()

1.0